version: "3"

services:
  web:
    build: ${APP_DOCKER_DIR}/web
    restart: 'always'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.php"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on: 
      - mariadb
    volumes:
      - ${APP_COVERAGE_DIR}:/xdebug/
    environment:
      JOOMLA_USERNAME: jAEkPot
      JOOMLA_PASSWORD: jAEkPot
        #JOOMLA_DATABASE_TYPE: mariadb
        #JOOMLA_DATABASE_HOST: db
      JOOMLA_DATABASE_USER: dbuser
      JOOMLA_DATABASE_PASSWORD: dbpassword
      JOOMLA_DATABASE_NAME: dbname
  mariadb:
    image: bitnami/mariadb:10.3 
    restart: 'always'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpassword
      MARIADB_DATABASE: dbname
      MARIADB_SQL_MODE: NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION
