version: "3"
services:
  crawler:
    build: ${CRAWLER_DOCKER_DIR}/
    shm_size: 2gb
    volumes:
      - ${CRAWLER_REPORT_DIR}:/opt/crawljax/out/
        #  web:
        #    image: dockercontainervm/phoenix-trello
        #    healthcheck:
        #      test: ["CMD", "curl", "-f", "http://localhost"]
        #      interval: 1m30s
        #      timeout: 10s
        #      retries: 3
        #      start_period: 40s
        #    environment:
        #      - "PATH=/root/.kiex/elixirs/elixir-1.3.1/bin:/root/.kiex/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        #      - "PORT=80"
        #    command: bash -c 'sed -i s/4000/80/g config/dev.exs && ./run-services-docker.sh'
