version: '3'
services:
  web:
    build: ${APP_DOCKER_DIR}/web
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on: 
      - mariadb
    volumes:
      - ${APP_COVERAGE_DIR}:/xdebug/
    environment:
      - OWNCLOUD_DATABASE_HOST=mariadb
      - OWNCLOUD_DATABASE_PORT_NUMBER=3306
      - OWNCLOUD_DATABASE_USER=bn_owncloud
      - OWNCLOUD_DATABASE_NAME=bitnami_owncloud
      - OWNCLOUD_USERNAME=jAEkPot
      - OWNCLOUD_PASSWORD=jAEkPot
      - OWNCLOUD_EMAIL=jaekpot@localhost.com
      - APACHE_HTTP_PORT_NUMBER=80
      - ALLOW_EMPTY_PASSWORD=yes
      - OWNCLOUD_HOST=web
  mariadb:
    image: bitnami/mariadb:10.3 
    restart: unless-stopped
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_owncloud
      - MARIADB_DATABASE=bitnami_owncloud
