version: "3"

services:
  web:
    build: ${APP_DOCKER_DIR}/web
    restart: 'always'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.php"]
      interval: 1m
      timeout: 10s
      retries: 10
      start_period: 5s
    depends_on: 
      - mariadb
    volumes:
      - ${APP_COVERAGE_DIR}:/xdebug/
    environment:
      DRUPAL_USERNAME: jAEkPot
      DRUPAL_PASSWORD: jAEkPot
      DRUPAL_DATABASE_USER: dbuser
      DRUPAL_DATABASE_PASSWORD: dbpassword
      DRUPAL_DATABASE_NAME: dbname
  mariadb:
    image: bitnami/mariadb:10.3 
    restart: 'always'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpassword
      MARIADB_DATABASE: dbname
