version: "3"

services:
  web:
    build: ${APP_DOCKER_DIR}/web
    restart: 'always'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.php"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - ${APP_COVERAGE_DIR}:/xdebug/
