<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/html
		/claroline-1.11.10
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date January 28, 2020 at 08:05 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLANNGenDate is an internal mark
   $CLANNGenDate = "1580198747";

/* announcementPortletMaxItems : Use 0 to display all */
$GLOBALS['announcementPortletMaxItems'] = 3;



?>