<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		/var
		/www
		/html
		/claroline-1.11.10
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date January 28, 2020 at 08:05 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLMSGGenDate is an internal mark
   $CLMSGGenDate = "1580198746";

/* messagePerPage : Number of message per page */
$GLOBALS['messagePerPage'] = 15;


/* mailNotification : Enable Email notification */
$GLOBALS['mailNotification'] = TRUE;


/* userCanSendMessage : Users can send messages from outside a course context */
$GLOBALS['userCanSendMessage'] = FALSE;



?>