version: "3"

services:
  web:
    build: ${APP_DOCKER_DIR}/web
    restart: 'always'
    healthcheck:
      test: curl -f http://web/ | grep PrestaShop
      interval: 1m
      timeout: 10s
      retries: 10
      start_period: 20s
    depends_on: 
      - mariadb
    volumes:
      - ${APP_COVERAGE_DIR}:/xdebug/
    environment:
      PRESTASHOP_HOST: web
      PRESTASHOP_USERNAME: jAEkPot
      PRESTASHOP_EMAIL: jaekpot@localhost.com
      PRESTASHOP_PASSWORD: jAEkPot
      PRESTASHOP_DATABASE_USER: dbuser
      PRESTASHOP_DATABASE_PASSWORD: dbpassword
      PRESTASHOP_DATABASE_NAME: dbname
  mariadb:
    image: bitnami/mariadb:10.3 
    restart: 'always'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpassword
      MARIADB_DATABASE: dbname
      MARIADB_SQL_MODE: NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION
